version: '3.8'
services:
  server-trybesocial:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: trybesocialdb
      POSTGRES_PASSWORD: Tryber@123
      POSTGRES_DB: nest
    networks:
     - trybesocialnet
networks:
  trybesocialnet: